using System.ComponentModel;
using ModelContextProtocol.Server;
using ScriptBee.MCP.Gateway.Generated;
using ScriptBee.MCP.Gateway.Generated.Contracts;

namespace ScriptBee.MCP.Tools;

[McpServerToolType]
public sealed class AnalysisTools(IGatewayApi gatewayApi)
{
    [McpServerTool]
    [Description("Lists all analyses performed within the specified project.")]
    public async Task<AnalysisListResponse> GetAnalyses(
        [Description("The unique identifier of the project.")] string projectId,
        [Description("Sort order for results (e.g. 'createdAt:desc').")] string? sort,
        CancellationToken cancellationToken
    ) => await gatewayApi.AnalysesGet2(projectId, sort ?? "", cancellationToken);

    [McpServerTool]
    [Description("Triggers a new analysis for a project instance by running a specific script.")]
    public async Task TriggerAnalysis(
        [Description("The unique identifier of the project.")] string projectId,
        [Description("The unique identifier of the instance to run the analysis on.")]
            string instanceId,
        [Description("The unique identifier of the script to execute.")] string scriptId,
        CancellationToken cancellationToken
    ) =>
        await gatewayApi.Analyses(
            projectId,
            instanceId,
            new TriggerAnalysisCommand { ScriptId = scriptId },
            cancellationToken
        );

    [McpServerTool]
    [Description("Retrieves the current status and details of a specific analysis.")]
    public async Task<AnalysisInfo> GetAnalysisStatus(
        [Description("The unique identifier of the project.")] string projectId,
        [Description("The unique identifier of the analysis.")] string analysisId,
        CancellationToken cancellationToken
    ) => await gatewayApi.AnalysesGet(projectId, analysisId, cancellationToken);

    [McpServerTool]
    [Description("Deletes a specific analysis and all its associated result files.")]
    public async Task DeleteAnalysis(
        [Description("The unique identifier of the project.")] string projectId,
        [Description("The unique identifier of the analysis to delete.")] string analysisId,
        CancellationToken cancellationToken
    ) => await gatewayApi.AnalysesDelete(projectId, analysisId, cancellationToken);

    [McpServerTool]
    [Description("Retrieves the console output produced during a specific analysis execution.")]
    public async Task<GetAnalysisResultConsole> GetAnalysisConsole(
        [Description("The unique identifier of the project.")] string projectId,
        [Description("The unique identifier of the analysis.")] string analysisId,
        CancellationToken cancellationToken
    ) => await gatewayApi.Console(projectId, analysisId, cancellationToken);

    [McpServerTool]
    [Description(
        "Retrieves the list of errors that occurred during a specific analysis execution."
    )]
    public async Task<GetAnalysisResultRunErrors> GetAnalysisErrors(
        [Description("The unique identifier of the project.")] string projectId,
        [Description("The unique identifier of the analysis.")] string analysisId,
        CancellationToken cancellationToken
    ) => await gatewayApi.Errors(projectId, analysisId, cancellationToken);

    [McpServerTool]
    [Description("Lists all output files generated by a specific analysis.")]
    public async Task<GetAnalysisResultFileList> GetAnalysisResultFiles(
        [Description("The unique identifier of the project.")] string projectId,
        [Description("The unique identifier of the analysis.")] string analysisId,
        CancellationToken cancellationToken
    ) => await gatewayApi.FilesGet3(projectId, analysisId, cancellationToken);

    [McpServerTool]
    [Description("Retrieves metadata about a script used in a specific analysis.")]
    public async Task<ScriptData> GetAnalysisScript(
        [Description("The unique identifier of the project.")] string projectId,
        [Description("The unique identifier of the analysis.")] string analysisId,
        [Description("The unique identifier of the script.")] string scriptId,
        CancellationToken cancellationToken
    ) => await gatewayApi.Scripts(projectId, analysisId, scriptId, cancellationToken);

    [McpServerTool]
    [Description("Retrieves the source code of a script as it was used in a specific analysis.")]
    public async Task<string> GetAnalysisScriptContent(
        [Description("The unique identifier of the project.")] string projectId,
        [Description("The unique identifier of the analysis.")] string analysisId,
        [Description("The unique identifier of the script.")] string scriptId,
        CancellationToken cancellationToken
    ) => await gatewayApi.Content(projectId, analysisId, scriptId, cancellationToken);
}
