version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/Integrations/VS-Code"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/Plugins/UI/default-scriptbee-charts"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
  
  - package-ecosystem: "npm"
    directory: "/ScriptBeeClient"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

cooldown:
  default-days: 7
