services:
  mongo:
    image: mongo:8.0.4
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.10
    container_name: mock-oauth2-server
    ports:
      - "8080:8080"

  opa:
    image: openpolicyagent/opa:1.19.1-static
    container_name: opa
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--addr=:8181"
      - "--log-level=info"
      - "/policies"
    volumes:
      - ./quickstart/full/policy.rego:/policies/policy.rego:ro
      - ./quickstart/full/roles.rego:/policies/roles.rego:ro

volumes:
  mongodb_data:
