<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ScriptBee.Tests.Common.Mongodb</RootNamespace>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="Testcontainers.MongoDb" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tests.Common\Tests.Common.csproj" />
  </ItemGroup>
</Project>
