name: scriptbee-quickstart-full

services:
  mongo:
    image: mongo:8.0.4
    container_name: scriptbee-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  opa:
    image: openpolicyagent/opa:1.19.1-static
    command:
      - "run"
      - "--server"
      - "--addr=:8181"
      - "--log-level=info"
      - "/policies"
    ports:
      - "8181:8181"
    volumes:
      - ./full/policy.rego:/policies/policy.rego:ro
      - ./full/roles.rego:/policies/roles.rego:ro

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: http://localhost:8082
      KC_HOSTNAME_STRICT: "false"
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - ./full/realm-export.json:/opt/keycloak/data/import/realm.json:ro
    ports:
      - "8082:8080"
    restart: unless-stopped

  scriptbee:
    image: dxworks/scriptbee:latest
    user: root
    ports:
      - "4201:80"
    volumes:
      - ./data:/root/.scriptbee
      - ./plugins:/app/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ConnectionStrings__mongodb=mongodb://root:example@scriptbee-mongo:27017/ScriptBee?authSource=admin
      - UserFolder__UserFolderPath=/root/.scriptbee
      - AUTHENTICATION__AUTHORITY=http://localhost:8082/realms/scriptbee
      - AUTHENTICATION__AUDIENCE=scriptbee-api
      - AUTHENTICATION__CLIENTID=scriptbee-client
      - AUTHENTICATION__REQUIREHTTPSMETADATA=false
      - AUTHENTICATION__SCOPE=openid profile email
      - AUTHENTICATION__EXTERNALAUTHORIZATIONURL=http://opa:8181/v1/data/scriptbee/auth/allow
      - AUTHENTICATION__PERMISSIONSURL=http://opa:8181/v1/data/scriptbee/auth/user_permissions
      - AUTHENTICATION__ROLESURL=http://opa:8181/v1/data/scriptbee/auth/roles_and_permissions/roles
      - AUTHENTICATION__DEFAULTCREATORROLEURL=http://opa:8181/v1/data/scriptbee/auth/roles_and_permissions/default_creator_role
      - SCRIPTBEE__ANALYSIS__DRIVER=docker
      - SCRIPTBEE__ANALYSIS__DOCKER__NETWORK=scriptbee-quickstart-full_default
      - SCRIPTBEE__ANALYSIS__DOCKER__DOCKERSOCKET=unix:///var/run/docker.sock
      - SCRIPTBEE__ANALYSIS__DOCKER__USERFOLDERHOSTPATH=${PWD}/data
      - SCRIPTBEE__ANALYSIS__DOCKER__LABELS__com.docker.compose.project=scriptbee-quickstart-full
      - SCRIPTBEE__PLUGINS__INSTALLATIONFOLDER=/app/plugins
    depends_on:
      - mongo
      - keycloak
      - opa

volumes:
  mongodb_data:
