<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ScriptBee.Adapters.Auth.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="WireMock.Net" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Gateway\Adapters\Auth\Auth.csproj" />
    <ProjectReference Include="..\..\..\Common\Tests.Common\Tests.Common.csproj" />
  </ItemGroup>
</Project>
