<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
    <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Westwind.Utilities" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\DxWorks.ScriptBee.Plugin.Api\DxWorks.ScriptBee.Plugin.Api.csproj" />
    <ProjectReference Include="..\..\..\ScriptBeeWebApp\src\Common\CodeGeneration\CodeGeneration.csproj" />
  </ItemGroup>
</Project>
