name: Plugin API CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'DxWorks.ScriptBee.Plugin.Api/**'
      - '.github/workflows/plugin-api-ci.yml'
  pull_request:
    paths:
      - 'DxWorks.ScriptBee.Plugin.Api/**'
      - '.github/workflows/plugin-api-ci.yml'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore, Build and Pack
        run: |
          dotnet restore DxWorks.ScriptBee.Plugin.Api/DxWorks.ScriptBee.Plugin.Api.csproj
          dotnet build DxWorks.ScriptBee.Plugin.Api/DxWorks.ScriptBee.Plugin.Api.csproj --no-restore
          dotnet pack DxWorks.ScriptBee.Plugin.Api/DxWorks.ScriptBee.Plugin.Api.csproj --no-build -c Release
