name: Release Docs
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Install MkDocs
        run: pip install mkdocs-material mkdocs-material-extensions
        
      - name: Deploy docs
        run: mkdocs gh-deploy --force
