name: UI CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'ScriptBeeClient/**'
      - '.github/workflows/ui-ci.yml'
  pull_request:
    paths:
      - 'ScriptBeeClient/**'
      - '.github/workflows/ui-ci.yml'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ScriptBeeClient

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: ScriptBeeClient/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Get Playwright version
        id: playwright-version
        shell: bash
        run: |
          PLAYWRIGHT_VERSION=$(npm list @vitest/browser-playwright --json | jq -r '.dependencies["@vitest/browser-playwright"].version')
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache Playwright binaries
        uses: actions/cache@v5
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install chromium --with-deps

# TODO FIXIT(#123): uncomment when eslint issues are fixed
#      - name: Lint
#        run: npm run lint

      - name: Run Tests
        run: npm run test:ci

      - name: Build
        run: npm run build
